/// Flutter icons Scales
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Scales
///      fonts:
///       - asset: fonts/Scales.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Scales {
  Scales._();

  static const _kFontFam = 'Scales';
  static const String? _kFontPkg = null;

  static const IconData scale =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
